config/routes.rb
HomeCinema::Application.routes.draw do
  
  get 'admin', controller: 'admin', action: 'index'

  resources :shows, shallow: true do
		resources :movie_suggestions, path: :suggestions
		resources :registrations, except: :destroy do
			resources :votes, only: [:index, :create]
			resource :movie_suggestion, path: :suggestion
		end
	end

	resources :seats
  resources :movies do
		get 'search', on: :collection
	end

end

app/models/seat.rb
class Seat < ActiveRecord::Base
  attr_accessible :image,	:name, :position_x, :position_y

	has_many :seat_reservations, dependent: :destroy
	has_attached_file :image,
										styles: { sized: 'x150' },
										path: ':rails_root/public/system/:class/:attachment/:id/:style/:filename',
										url: '/system/:class/:attachment/:id/:style/:filename'

	validates :name, presence: true, uniqueness: {case_sensitive: false}
	validates_attachment :image, presence: true, content_type: { content_type: /image\/[\w\-]*(?:jpe?g|png|gif)$/i }

end

app/controllers/seats_controller.rb
class SeatsController < ApplicationController
  # GET /seats
  # GET /seats.json
  def index
  end

  # GET /seats/1
  # GET /seats/1.json
  def show
    @seat = Seat.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @seat }
    end
  end

  # GET /seats/new
  # GET /seats/new.json
  def new
    @seat = Seat.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @seat }
    end
  end

  # GET /seats/1/edit
  def edit
    @seat = Seat.find(params[:id])
  end

  # POST /seats
  # POST /seats.json
  def create
    @seat = Seat.new(params[:seat])
		filename = @seat.image.original_filename
		@seat.name = File.basename(filename, File.extname(filename)).humanize

    if @seat.save
			render json: {
				id: @seat.id,
				html: render_to_string(@seat, formats: :html)
			}
    else
			render json: @seat.errors, status: :unprocessable_entity
		end
  end

  # PUT /seats/1
  # PUT /seats/1.json
  def update
    for seat in Seat.all
			seat_data = params[seat.id.to_s]
			if seat_data
				seat.update_attributes(seat_data)
			else
				seat.destroy
			end
		end

		#TODO: error handling
    render json: {sucess: true}
  end

  # DELETE /seats/1
  # DELETE /seats/1.json
  def destroy
    @seat = Seat.find(params[:id])
    @seat.destroy

    respond_to do |format|
      format.html { redirect_to seats_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/seats_helper.rb
module SeatsHelper
	def get_seat_class(seat, registration)
		html_class = 'seat'
		if registration.present?
			html_class += ' selected' if registration.seat_reservations.any? { |sr| sr.seat == seat }
			html_class += ' taken' unless registration.show.seat_available?(seat)
		end
		return html_class
	end
end

app/views/seats/_seat.html.erb
<%= content_tag :div, id: 'seat'+seat.id.to_s, data: {id: seat.id, name: seat.name}, class: get_seat_class(seat, @registration), style: (
		"left: #{seat.position_x}px; " +
		"top: #{seat.position_y}px; " +
		"width: #{seat.image.width(:sized)}px; " +
		"height: #{seat.image.height(:sized)}px; " +
		"background: transparent url('#{seat.image.url(:sized)}') no-repeat center center; ") do -%>
	<div class="occupancy"></div>
<% end -%>

app/views/seats/_seat_info.html.erb
<div id="seat_info" class="span4" style="display: none;">
	<%= simple_form_for 'seat' do |f| %>
		<%= f.input :name, required: false %>
		<%= f.input :position_x, label: 'X', required: false %>
		<%= f.input :position_y, label: 'Y', required: false %>
	<% end %>
	<button id="delete_seat" type="button" class="btn btn-danger">
		<i class="icon-trash icon-white"></i>
		<span>Sitz löschen</span>
	</button>
</div>

app/views/seats/_seat_plan.html.erb
<div id="seat_plan" class="span8">
	<%= render Seat.all %>
</div>

app/views/seats/_seat_upload.html.erb
<%= form_for 'seat', url: seats_path, html: {id: 'seat_upload', class: 'form-inline'} do |f| %>
	<span class="btn fileinput-button">
		<i class="icon-upload"></i>
		<span>Sitz hinzuf&uuml;gen</span>
		<%= f.file_field :image %>
	</span>
<% end %>

app/views/seats/edit.html.erb
<h1>Editing seat</h1>

<%= render 'form' %>

<%= link_to 'Show', @seat %> |
<%= link_to 'Back', seats_path %>

app/views/seats/index.html.erb
<div id="seats_header" class="page-header">
	<h1>Sitzplatzverwaltung</h1>
</div>

<div class="row">
	<%= render 'seat_plan' %>
	<%= render 'seat_info' %>
</div>

<div id="seat_actions">
	<%= render 'seat_upload' %>
	<button id="save_seats_btn" type="button" class="btn btn-primary">
		<span>Speichern</span>
	</button>
	<%= link_to 'Zurück', admin_path, class: 'btn' %>
</div>

app/views/seats/new.html.erb
<h1>New seat</h1>

<%= render 'form' %>

<%= link_to 'Back', seats_path %>

app/views/seats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @seat.name %>
</p>

<p>
  <b>Image path free:</b>
  <%= @seat.image_path_free %>
</p>

<p>
  <b>Image path selected:</b>
  <%= @seat.image_path_selected %>
</p>

<p>
  <b>Image path taken:</b>
  <%= @seat.image_path_taken %>
</p>

<p>
  <b>Position x:</b>
  <%= @seat.position_x %>
</p>

<p>
  <b>Position y:</b>
  <%= @seat.position_y %>
</p>


<%= link_to 'Edit', edit_seat_path(@seat) %> |
<%= link_to 'Back', seats_path %>