config/routes.rb
HomeCinema::Application.routes.draw do
  
  get 'admin', controller: 'admin', action: 'index'

  resources :shows, shallow: true do
		resources :movie_suggestions, path: :suggestions
		resources :registrations, except: :destroy do
			resources :votes, only: [:index, :create]
			resource :movie_suggestion, path: :suggestion
		end
	end

	resources :seats
  resources :movies do
		get 'search', on: :collection
	end

end

app/models/movie_suggestion.rb
require 'status'
class MovieSuggestion < ActiveRecord::Base
	STATUSES = [Status::PENDING, Status::ACCEPTED, Status::DENIED]

  attr_accessible :comment, :movie_id, :registration_code, :show_id,
									:movie, :registration, :show, :status

	belongs_to :movie
	belongs_to :registration
	belongs_to :show
	has_many :votes, dependent: :destroy

	validates :show, presence: true
	validates :movie, presence: {message: I18n.t('activerecord.errors.messages.no_movie')}
	validates :movie_id, uniqueness: {scope: :show_id, message: I18n.t('activerecord.errors.messages.duplicate_movie')}
	validates :status, inclusion: STATUSES
	validate :suggestions_allowed_for_show

	def registration_code=(code)
		self.registration = Registration.find_by_code(code)
	end

	def registration_code
		registration.code unless registration.nil?
	end

	protected
	def suggestions_allowed_for_show
		if registration
			errors.add(:base, I18n.t('activerecord.errors.messages.no_suggestions_allowed')) unless show.movie_suggestions_allowed
		end
	end
end

app/controllers/movie_suggestions_controller.rb
	class MovieSuggestionsController < ApplicationController

	before_filter :init

	# GET /movie_suggestions
  # GET /movie_suggestions.json
  def index		
    @movie_suggestions = @show.movie_suggestions

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @movie_suggestions }
    end
  end

  # GET /movie_suggestions/1
  # GET /movie_suggestions/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @movie_suggestion }
    end
  end

  # GET /movie_suggestions/new
  # GET /movie_suggestions/new.json
  def new
		@movie_suggestion = @show.movie_suggestions.build(movie_id: params[:movie_id])
		@movie = @movie_suggestion.movie || Movie.new
		
    respond_to do |format|
			format.js
      format.html # new.html.erb
    end
  end

  # GET /movie_suggestions/1/edit
  def edit
    @movie = @movie_suggestion.movie
  end

  # POST /movie_suggestions
  # POST /movie_suggestions.json
  def create
		@movie_suggestion = @show.movie_suggestions.build(params[:movie_suggestion])
		@movie_suggestion.status = @registration ? Status::PENDING : Status::ACCEPTED

    respond_to do |format|
      if @movie_suggestion.save
        format.html { redirect_to @return_url, notice: I18n::t('notice.suggestion.created') }
      else
        format.html do
					flash_errors
					@movie = @movie_suggestion.movie || Movie.new
					render action: "new"
				end
      end
    end
  end

  # PUT /movie_suggestions/1
  # PUT /movie_suggestions/1.json
  def update
		respond_to do |format|
      if @movie_suggestion.update_attributes(params[:movie_suggestion])
        format.html { redirect_to @return_url, notice: I18n::t('notice.suggestion.updated') }
      else
        format.html do
					flash_errors
					@movie = @movie_suggestion.movie
					render action: "edit"
				end
      end
    end
  end

  # DELETE /movie_suggestions/1
  # DELETE /movie_suggestions/1.json
  def destroy
    @movie_suggestion.destroy

    respond_to do |format|
      format.html { redirect_to @return_url, notice: I18n::t('notice.suggestion.deleted') }
    end
  end

	protected
	def init

		if params[:registration_id]
			begin
				@registration = Registration.find_by_code!(params[:registration_id])
				@movie_suggestion = @registration.movie_suggestion
				@show = @registration.show
				@return_url = registration_url(@registration)
				@form_path = registration_movie_suggestion_path(@registration.code)
				unless @movie_suggestion || ['new', 'create'].include?(action_name)
					logger.error("Attempt to modify non-existing movie suggestion for registration ##{params[:registration_id]}")
					redirect_to @return_url, alert: I18n::t('alert.suggestion.not_found')
				end
			rescue ActiveRecord::RecordNotFound
				logger.error("Attempt to access invalid registration ##{params[:registration_id]}")
				redirect_to shows_url, alert: I18n::t('alert.registration.invalid_code')
			end
		else
			check_admin
			if params[:id]
				begin
					@movie_suggestion = MovieSuggestion.find(params[:id])
					@show = @movie_suggestion.show
					@form_path = movie_suggestion_path(@movie_suggestion)
				rescue ActiveRecord::RecordNotFound
					logger.error("Attempt to access invalid movie suggestion ##{params[:id]}")
					redirect_to admin_url, alert: I18n::t('alert.suggestion.not_found')
				end
			elsif params[:show_id]
				begin
					@show = Show.find(params[:show_id])
					@form_path = show_movie_suggestions_path(@show)
				rescue ActiveRecord::RecordNotFound
					logger.error("Attempt to access invalid show ##{params[:show_id]}")
					redirect_to admin_url, alert: I18n::t('alert.show.not_found')
				end
			end
			@return_url = show_movie_suggestions_url(@show)
		end
	end

	def flash_errors
		flash.now[:error] = @movie_suggestion.errors.values.join('<br/>')
	end

end

app/helpers/movie_suggestions_helper.rb
module MovieSuggestionsHelper
end

app/views/movie_suggestions/_form.html.erb
<%= render 'movie_search' %>
<div class="movie-wrapper clearfix">
	<%= render @movie unless @movie.new_record? %>
</div>
<%= simple_form_for @movie_suggestion, url: @form_path do |f| %>
	<%= f.input_field :movie_id, as: :hidden %>
	<%= f.input :comment, input_html: {class: 'span9', rows: 8},
				hint: 'Wenn du noch etwas über den Film schreiben möchtest, kannst du das hier tun.'%>
	<%= f.button :submit, 'Speichern', class: 'btn-primary' %>
	<%= link_to 'Löschen', @movie_suggestion, confirm: 'Wirklich löschen?', 
				method: :delete, class: 'btn btn-danger' unless @movie_suggestion.new_record? %>
	<%= link_to 'Zurück', :back, class: 'btn' %>
<% end %>
<%= render 'modals' %>

app/views/movie_suggestions/_modals.html.erb
<div id="movie_suggestion_box"></div>
<div id="search_modal" class="modal fade">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal">&times;</button>
		<h2 id="search_header"></h2>
	</div>
	<div id="search_results" class="modal-body">
		<%= image_tag 'loader.gif', class: 'loader' %>
	</div>
	<div id="search_nav" class="pagination pagination-centered"></div>
</div>
<div id="movie_form_modal" class="modal fade">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal">&times;</button>
		<h2>Film erfassen</h2>
	</div>
	<%= render 'movies/form', modal: true %>
</div>

app/views/movie_suggestions/_movie_search.html.erb
<form accept-charset="UTF-8" action="/movies/search" class="form-horizontal <%='hide' unless @movie.new_record? %>"
			data-remote="true" data-type="json" id="movie_search_form" method="get" novalidate="novalidate">
	<input name="utf8" type="hidden" value="✓" />	
	<label for="movie_search_input">Film</label>
	<div class="input-append">
		<input class="autocomplete" data-autocomplete="/movies/search"
					id="movie_search_input" name="query" size="30" placeholder="Suchen"
					 type="search" url="/movies/search" /><button class="btn" type="submit">
			<i class="icon-search"></i></button>
	</div>
	<span class="help-inline">oder <a id="movie_form_toggle" data-toggle="modal" href="#movie_form_modal">manuell erfassen</a></span>
</form>
<button id="movie_change_button" class="btn <%='hide' if @movie.new_record? %>">Film ändern</button>

app/views/movie_suggestions/_movie_suggestion.html.erb
<div id="<%="suggestion#{movie_suggestion.id}"%>" class="movie-suggestion">
	<% if edit %>
		<%= link_to 'Löschen', movie_suggestion, confirm: 'Wirklich löschen?', method: :delete, class: 'btn btn-danger delete-suggestion' %>
		<%= link_to 'Bearbeiten', edit_movie_suggestion_path(movie_suggestion), class: 'btn edit-suggestion' %>
	<% end %>
	<div class="movie-wrapper clearfix">
		<%= render movie_suggestion.movie %>
	</div>
	<% if movie_suggestion.comment.present? %>
		<div class="suggestion-comment">
			Anmerkung<%=' von ' + movie_suggestion.registration.name if movie_suggestion.registration.present? %>:
			<p><%= movie_suggestion.comment %></p>
		</div>
	<% end %>
</div>

app/views/movie_suggestions/_preview.html.erb
<%= link_to send(@admin ? :show_movie_suggestions_path : :show_path, preview.show, anchor: "suggestion#{preview.id}") do %>
	<%= render partial: 'movies/preview', object: preview.movie, locals: {format: 'poster_large'} %>
<% end %>

app/views/movie_suggestions/edit.html.erb
<div class="page-header">
	<h1>Filmvorschlag bearbeiten</h1>
</div>
<%= render 'form' %>

app/views/movie_suggestions/index.html.erb
<div id="suggestions_header" class="page-header">
	<h1>Filmvorschläge für <%=l! @show.date.to_date %></h1>
</div>
<%= render @movie_suggestions, edit: true %>
<%= link_to 'Neuer Filmvorschlag', new_show_movie_suggestion_path(@show), class: 'btn' %>

app/views/movie_suggestions/new.html.erb
<div class="page-header">
	<h1>Neuer Filmvorschlag für <%=l! @show.date.to_date %></h1>
</div>
<%= render 'form' %>

app/views/movie_suggestions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Movie:</b>
  <%= @movie_suggestion.movie_id %>
</p>

<p>
  <b>Show:</b>
  <%= @movie_suggestion.show_id %>
</p>

<p>
  <b>Registration:</b>
  <%= @movie_suggestion.registration_id %>
</p>

<p>
  <b>Comment:</b>
  <%= @movie_suggestion.comment %>
</p>


<%= link_to 'Edit', edit_movie_suggestion_path(@movie_suggestion) %> |
<%= link_to 'Back', movie_suggestions_path %>