config/routes.rb
HomeCinema::Application.routes.draw do
  
  get 'admin', controller: 'admin', action: 'index'

  resources :shows, shallow: true do
		resources :movie_suggestions, path: :suggestions
		resources :registrations, except: :destroy do
			resources :votes, only: [:index, :create]
			resource :movie_suggestion, path: :suggestion
		end
	end

	resources :seats
  resources :movies do
		get 'search', on: :collection
	end

end

app/controllers/movies_controller.rb
require 'moviepilot_api'
class MoviesController < ApplicationController
  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @movies }
    end
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
    @movie = Movie.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render_as_json }
    end
  end

  # GET /movies/new
  # GET /movies/new.json
  def new
    @movie = Movie.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @movie }
    end
  end

  # GET /movies/1/edit
  def edit
    @movie = Movie.find(params[:id])
  end

  # POST /movies
  # POST /movies.json
  def create
		@movie = Movie.new(params[:movie])
		
    respond_to do |format|
      if @movie.save
				format.json { render_as_json }
				format.html { render_as_json(true) }
      else
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /movies/1
  # PUT /movies/1.json
  def update
    @movie = Movie.find(params[:id])

    respond_to do |format|
      if @movie.update_attributes(params[:movie])
        format.json { render_as_json }
				format.html { render_as_json(true) }
      else
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy

    respond_to do |format|
      format.html { redirect_to movies_url }
      format.json { head :no_content }
    end
  end

	def search
		search_query = (params[:query] || params[:term] || '').strip.downcase
		popup = params[:term].present?

		if search_query.length > 1
			@page = (params[:page] || 1).to_i
			@movie_search = MovieSearch.find_or_initialize_by_query(search_query)

			MovieSearch.transaction do
				@movies, @suggestions = get_from_cache || get_from_api
			end

			respond_to do |format|
				format.json do
					if @movies
						return render_popup_results if popup
						render json: {
							results: render_to_string(partial: 'movies/preview', collection: @movies, formats: :html),
							header: render_to_string(partial: 'movies/search/header', formats: :html),
							navigation: render_to_string(partial: 'movies/search/navigation', formats: :html)
						}
					else
						return head :no_content if popup
						partial, status = (@suggestions.nil?) ? ['error', 500] : (@suggestions.empty?) ? ['no_results', 404] : ['suggestions', 300]
						render text: render_to_string(partial: 'movies/search/' + partial, formats: :html, status: status)
					end
				end
			end
		else
			head :no_content
		end
	end

	private
	def get_from_cache
		# return immediately if this is a new search
		unless @movie_search.new_record?
			# init variables
			from = (@page - 1) * 5;	to = @page * 5
			# do DB query
			movies = MovieSearchResult.where(
				movie_search_id: @movie_search.id,
				result_number: [from...to]
			).map { |result| result.movie }
			# calculate expected return count
			expected_return_count = [5, @movie_search.total_results - from].min
			# only return DB result if count matches
			if expected_return_count == movies.size
				logger.info "Returning results #{from+1}-#{to} for query '#{@movie_search.query}' from cache"
				return movies, nil
			else
				unless movies.empty?
					# delete all cached results unless no results at all were returned
					logger.warn "Inconsistent cache lookup! Destroying cached results for query '#{@movie_search.query}'"
					@movie_search.results.clear
				end
				return nil
			end
		end
	end

	def get_from_api
		# initialize API
		api = MoviepilotApi.new(Settings.moviepilot.api.key)

		# send search request to API
		response_data = api.movie_search(@movie_search.query, {per_page: 5, page: @page}, {timeout: 5}) rescue nil
		# return nil if the API didn't return a result in time
		return nil unless response_data.is_a? Hash
		if response_data.has_key? 'total_entries' and response_data['total_entries'] > 0
			# set total results
			@movie_search.total_results = response_data['total_entries']
			# save the MovieSearch object
			@movie_search.save
			# calculate result offset
			offset = (@page - 1) * 5
			# iterate over the returned movie results
			movies = response_data['movies'].each_with_index.map do |movie_data, i|
				# build a Movie object from the returned data...
				movie = Movie.build_from_api_result(movie_data)
				# ...and try to save it
				if movie.save
					# if successful, build an MovieSearchResult from it
					# and add the movie object to the return array
					@movie_search.results.build(
						movie: movie,
						result_number: i + offset
					).movie
				else
					# if the save operation failed, log an error...
					logger.error "Movie could not be saved! Object: #{movie.attributes}; Errors: #{movie.errors.to_a}"
					# and add nil to the return array
					nil
				end
			end

			# try to save the MovieSearch object again; destroy it on fail
			@movie_search.save || @movie_search.destroy && logger.warn(
				'MovieSearch could not be saved and was therefore destroyed! ' +
				"Errors: #{@movie_search.errors.to_a}")

			# remove all nil entries from the return array and return it
			logger.info "Returning results #{offset+1}-#{offset+5} for query '#{@movie_search.query}' from API"
			return movies.compact, nil

		elsif response_data.has_key? 'suggestions'
			# return the array of search suggestions if present
			return nil, response_data['suggestions']
		else
			# return nil if neither movie results nor suggestions were returned
			return nil
		end
	end

	def render_popup_results
		result = @movies.map do |movie|
			{	label: render_to_string(partial: 'movies/preview', formats: :html, object: movie),
				value: '',
				id: movie.id }
		end
		if @movie_search.total_results > 5
			result << { label: "<em>Alle #{@movie_search.total_results} Treffer anzeigen</em>",
									value: params[:term],
									show_all: true }
		end
		render json: result
	end

	def render_as_json(escape=false)
		movie_html = render_to_string(@movie, formats: :html)
		movie_html = CGI::escape_html(movie_html.gsub('"', "'")) if escape
		render json: { movie: movie_html, movie_id: @movie.id }
	end
end

app/helpers/movies_helper.rb
module MoviesHelper
	def poster_url(movie, format)
		if movie.poster_file_size
			movie.poster.url(format.to_sym)
		elsif movie.moviepilot_image_url
			movie.moviepilot_image_url.gsub(/\.(jpg|jpeg|png|gif)$/i, "_#{format}.\\1")
		else
			'placeholder.png'
		end
	end

	def format_description(description, shorten=true)
		simple_format(first_words(html_escape(description), shorten ? 130 : -1), {}, sanitize: false)
		.gsub(/\*([^*]+)\*/, '<strong>\1</strong>')
		.html_safe
	end
end

app/views/movies/_form.html.erb
<%= simple_form_for @movie, html: {multipart: true, id: 'movie_form', class: "form-horizontal #{'modal-form' if modal}"} do |f| %>
	<div class="<%=modal ? 'modal-body' : 'form-body'%>">
		<%= f.input :title, input_html: {class: 'span4', required: 'required'} %>
		<%= f.input :description, input_html: {rows: 10, class: 'span4', required: 'required'} %>
		<%= f.input :poster, as: :file, input_html: {class: 'span6'} %>
		<%= f.input :production_year, as: :string, required: true, input_html: {class: 'span1', required: 'required'} %>
		<%= f.input :runtime, as: :string, required: true, input_html: {class: 'span1', required: 'required'} %>
	</div>
	<div class="<%=modal ? 'modal-footer' : 'form-actions'%>">
		<a data-dismiss="modal" class="btn">Abbrechen</a>
		<%= f.button :submit, 'Übernehmen', class: 'btn-primary', id: 'movie_submit', :'data-loading-text' => 'Senden…' %>
	</div>
<% end %>

app/views/movies/_movie.html.erb
<div class="movie-poster">
	<%= image_tag poster_url(movie, 'normal'),
		alt: "Poster zu #{movie.title}", width: '200' %>
</div>
<div class="movie-text">
	<span class="movie-title"><%=h movie.title %></span>
	<% if movie.production_year %>
		<span class="movie-year">(<%= movie.production_year %>)</span>
	<% end %>
	<div class="movie-description read-more-short">
		<%= format_description movie.description %>
	</div>
	<div class="movie-description read-more-full">
		<%= format_description movie.description, false %>
	</div>
	<%= link_to "Mehr Infos, Bilder und Trailer auf www.moviepilot.de",
				movie.moviepilot_url, target: :_blank, class: 'moviepilot-link' if movie.moviepilot_url%>
</div>

app/views/movies/_preview.html.erb
<% format ||= 'poster' %>
<div class="movie-preview clearfix">
	<div class="movie-poster">
		<%= image_tag poster_url(preview, format),
			alt: "Poster zu #{preview.title}", width: (format=='poster') ? 60 : 108 %>
	</div>
	<div class="movie-text">
		<span class="movie-title"><%=h preview.title %></span>
		<% if preview.production_year %>
		<span class="movie-year">(<%= preview.production_year %>)</span>
		<% end %>
	</div>
	<% if params[:query].present? %>
		<button class="btn movie-select" data-id="<%=preview.id%>">&Uuml;bernehmen</button>
	<% end %>
</div>

app/views/movies/edit.html.erb
<h1>Editing movie</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<h1>Listing movies</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Length</th>
    <th>Year</th>
    <th>Comment</th>
    <th>Registration</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @movies.each do |movie| %>
  <tr>
    <td><%= movie.title %></td>
    <td><%= movie.description %></td>
    <td><%= movie.length %></td>
    <td><%= movie.year %></td>
    <td><%= movie.comment %></td>
    <td><%= movie.registration_id %></td>
    <td><%= link_to 'Show', movie %></td>
    <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
    <td><%= link_to 'Destroy', movie, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Movie', new_movie_path %>

app/views/movies/new.html.erb
<h1>New movie</h1>

<%= render 'form' %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @movie.title %>
</p>

<p>
  <b>Description:</b>
  <%= @movie.description %>
</p>

<p>
  <b>Length:</b>
  <%= @movie.length %>
</p>

<p>
  <b>Year:</b>
  <%= @movie.year %>
</p>

<p>
  <b>Comment:</b>
  <%= @movie.comment %>
</p>

<p>
  <b>Registration:</b>
  <%= @movie.registration_id %>
</p>


<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>