config/routes.rb
HomeCinema::Application.routes.draw do
  
  get 'admin', controller: 'admin', action: 'index'

  resources :shows, shallow: true do
		resources :movie_suggestions, path: :suggestions
		resources :registrations, except: :destroy do
			resources :votes, only: [:index, :create]
			resource :movie_suggestion, path: :suggestion
		end
	end

	resources :seats
  resources :movies do
		get 'search', on: :collection
	end

end

app/models/show.rb
require 'status'
class Show < ActiveRecord::Base
  attr_accessible :date, :movie_suggestions_allowed, :text

	has_many :registrations, dependent: :destroy
	has_many :accepted_registrations, class_name: 'Registration',
		conditions: {status: Status::ACCEPTED}
	has_many :pending_registrations, class_name: 'Registration',
		conditions: {status: Status::PENDING}
	has_many :cancelled_registrations, class_name: 'Registration',
		conditions: {status: Status::CANCELLED}
	has_many :denied_registrations, class_name: 'Registration',
		conditions: {status: Status::DENIED}

	has_many :movie_suggestions, dependent: :destroy
	has_many :accepted_user_suggestions, class_name: 'MovieSuggestion',
		conditions: "registration_id IS NOT NULL AND status == '#{Status::ACCEPTED}'"
	has_many :pending_user_suggestions, class_name: 'MovieSuggestion',
		conditions: "registration_id IS NOT NULL AND status == '#{Status::PENDING}'"
	has_many :own_suggestions, class_name: 'MovieSuggestion',
		conditions: {registration_id: nil, status: Status::ACCEPTED}

	belongs_to :featured_movie, class_name: 'Movie'
	has_many :votes, through: :registrations
	has_many :seat_reservations, through: :registrations

	validate :date_in_future

	def available_seats
		return Seat.all - seat_reservations.map {|sr| sr.seat}
	end

	def seat_available?(seat)
		return available_seats.include? seat
	end
	

	protected

	def date_in_future
		if date.nil?
			errors.add(:date, :blank)
		else
			errors.add(:date, 'muss in der Zukunft liegen.') unless date.future?
		end
	end
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  # GET /shows
  def index
    @shows = Show.where('date >= ?', DateTime.current)
		@admin = false
  end

  # GET /shows/1
  def show
    @show = Show.find(params[:id])
  end

  # GET /shows/new
  def new
    @show = Show.new
  end

  # GET /shows/1/edit
  def edit
    @show = Show.find(params[:id])
  end

  # POST /shows
  def create
    @show = Show.new(params[:show])
    if @show.save
			redirect_to admin_url, notice: 'Show was successfully created.'
    else
      render action: "new"
    end
  end

  # PUT /shows/1
  def update
    @show = Show.find(params[:id])
    if @show.update_attributes(params[:show])
			redirect_to admin_url, notice: 'Show was successfully updated.'
    else
			render action: "edit"
    end
  end

  # DELETE /shows/1
  def destroy
    @show = Show.find(params[:id])
    @show.destroy
    redirect_to admin_url
  end
end

app/helpers/shows_helper.rb
module ShowsHelper
	def submit_text
		if @show.new_record? then 'Weiter' else 'Speichern' end
	end
end

app/views/shows/_admin_actions.html.erb
<p class="registrations">
	<span class="accepted"><%= pluralize show.accepted_registrations.length, 'Anmeldung', 'Anmeldungen' -%></span>
	<span class="pending"><%= pluralize_if_any show.pending_registrations.length, 'Anfrage', 'Anfragen' -%></span>
</p>
<%= link_to 'Bearbeiten', edit_show_path(show), class: 'btn' %>
<%= link_to 'Filmvorschläge', show_movie_suggestions_path(show), class: 'btn' %>
<%= link_to 'Anmeldungen', show_registrations_path(show), class: 'btn' %>
<%= link_to 'Löschen', show, confirm: 'Wirklich löschen?', method: :delete,
		class: 'btn btn-danger' %>

app/views/shows/_form.html.erb
<%= simple_form_for @show, html: {class: 'form-horizontal'} do |f| %>
  <%= f.input :date, as: :string, input_html: {value: l(@show.date), class: 'span2'} %>
  <%= f.input :text, input_html: {class: 'span10'} %>
  <%= f.input :movie_suggestions_allowed %>
  <%= f.button :submit, submit_text, class: 'btn btn-primary' %>
	<%= link_to 'Abbrechen', admin_path, class: 'btn' %>
<% end %>

app/views/shows/_show.html.erb
<div class="show-container">
	<h3><%=l! show.date, format: :long %></h3>
	<p><%= show.text %></p>
	<h4>Filmvorschläge</h4>
	<div class="suggestions clearfix">
		<%= render partial: 'movie_suggestions/preview', collection: show.movie_suggestions %>
	</div>
	<div class="actions">
		<%= render (@admin ? 'shows/admin_actions' : 'shows/user_actions'), show: show %>
	</div>
</div>

app/views/shows/_user_actions.html.erb
<%= link_to 'Details anzeigen', show_path(show), class: 'btn' %>
<%= link_to 'Jetzt anmelden!', new_show_registration_path(show), class: 'btn btn-primary' %>

app/views/shows/edit.html.erb
<div class="page-header">
	<h1>Vorstellung bearbeiten</h1>
</div>
<%= render 'form' %>

app/views/shows/index.html.erb
<div class="page-header">
	<h1>Nächste Vorstellungen</h1>
</div>
<%= render @shows %>

app/views/shows/new.html.erb
<div class="page-header">
	<h1>Neue Vorstellung</h1>
</div>
<%= render 'form' %>

app/views/shows/show.html.erb
<div id="suggestions_header" class="page-header">
	<h1>Filmvorschläge für <%=l! @show.date.to_date %></h1>
</div>
<%= render @show.movie_suggestions, edit: false %>
<div id="actions">
	<%= link_to 'Jetzt anmelden!', new_show_registration_path(@show), class: 'btn btn-primary' %>
	<%= link_to 'Zurück zur Übersicht', shows_path, class: 'btn' %>
</div>